# Generated by Django 2.2 on 2019-04-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190406_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP')),
                ('ip_addr', models.CharField(max_length=30, verbose_name='IP address')),
                ('end_point', models.CharField(default='/', max_length=30, verbose_name='endpoint')),
                ('count', models.IntegerField(default=0, verbose_name='user visit number')),
            ],
            options={
                'verbose_name': 'User Visit Info',
                'verbose_name_plural': 'User Visit Info',
            },
        ),
        migrations.CreateModel(
            name='VisitNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='total visit number')),
            ],
            options={
                'verbose_name': 'total visit number',
                'verbose_name_plural': 'total visit number',
            },
        ),
    ]
