# Generated by Django 2.2 on 2019-04-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_userip_visitnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ip',
            field=models.CharField(default='', max_length=30, verbose_name='IP'),
        ),
    ]
