# Generated by Django 2.2 on 2019-04-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_message_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.CharField(choices=[('ONE', 'images/iphonex.png'), ('TWO', 'images/iphonex.png'), ('THREE', 'images/iphonex.png'), ('FOUR', 'images/iphonex.png')], default='', max_length=50, verbose_name='Photo'),
        ),
    ]
