# Generated by Django 2.2 on 2019-04-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_message_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.CharField(choices=[('ONE', 'images/fox.png'), ('TWO', 'images/koala.png'), ('THREE', 'images/squirrel.png'), ('FOUR', 'images/flamingo.png'), ('FOUR', 'images/elephant.png')], default='', max_length=50, verbose_name='Photo'),
        ),
    ]
