# Generated by Django 2.2 on 2019-04-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20190408_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.CharField(choices=[('ONE', 'images/fox.png'), ('TWO', 'images/koala.png'), ('THREE', 'images/squirrel.png'), ('FOUR', 'images/flamingo.png'), ('FOUR', 'images/elephant.jpg')], default='', max_length=50, verbose_name='Photo'),
        ),
    ]
