# Generated by Django 2.2 on 2019-04-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20190408_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='', max_length=50, verbose_name='host')),
                ('lan_ip', models.CharField(default='', max_length=50, verbose_name='lan_ip')),
                ('uuid', models.CharField(default='', max_length=50, verbose_name='uuid')),
                ('os_name', models.CharField(default='', max_length=50, verbose_name='os_name')),
            ],
        ),
    ]
